/** CampusPlug Runtime Debugger — sanitized client diagnostics. */
export type DebugLevel='trace'|'info'|'warn'|'error'|'success'
export type DebugCategory='app'|'network'|'supabase'|'auth'|'navigation'|'react'|'storage'|'performance'|'user'|'error'
export interface DebugEvent{ id:string; ts:string; level:DebugLevel; category:DebugCategory; message:string; data?:Record<string,unknown>; durationMs?:number; traceId?:string }
const KEY='cp_runtime_debugger_v1',MAX=1500,PERSIST=800,LIMIT=500
let events:DebugEvent[]=[];let listeners=new Set<(e:DebugEvent[])=>void>();let initialized=false;let paused=false;let originalConsole:Partial<Console>={};let originalFetch:typeof window.fetch|null=null
const nativeFetch=typeof window!=='undefined'?window.fetch.bind(window):null
const safe=(v:unknown):string=>{if(v instanceof Error)return `${v.name}: ${v.message}`;if(typeof v==='string')return v.slice(0,LIMIT);try{return JSON.stringify(v).slice(0,LIMIT)}catch{return String(v).slice(0,LIMIT)}}
const clean=(v:unknown,d=0):unknown=>{if(d>3)return '[depth-limit]';if(v==null||typeof v==='boolean'||typeof v==='number')return v;if(typeof v==='string')return v.slice(0,LIMIT);if(v instanceof Error)return{name:v.name,message:v.message,stack:v.stack?.split('\n').slice(0,8).join('\n')};if(Array.isArray(v))return v.slice(0,30).map(x=>clean(x,d+1));if(typeof v==='object'){const o:Record<string,unknown>={};for(const[k,x]of Object.entries(v as Record<string,unknown>).slice(0,40))o[k]=/authorization|apikey|token|password|cookie|secret|access_key|refresh/i.test(k)?'[redacted]':clean(x,d+1);return o}return safe(v)}
const notify=()=>listeners.forEach(fn=>{try{fn([...events])}catch{}});const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(events.slice(-PERSIST)))}catch{}};const id=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;const tid=()=>`tr-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`
export const debugLog=(level:DebugLevel,category:DebugCategory,message:string,data?:Record<string,unknown>,durationMs?:number,traceId?:string)=>{if(paused)return;events.push({id:id(),ts:new Date().toISOString(),level,category,message:message.slice(0,300),data:data?clean(data) as Record<string,unknown>:undefined,durationMs,traceId});if(events.length>MAX)events=events.slice(-MAX);persist();notify()}
export const debugTrace=(m:string,d?:Record<string,unknown>,t?:string)=>debugLog('trace','app',m,d,undefined,t);export const debugInfo=(c:DebugCategory,m:string,d?:Record<string,unknown>,t?:string)=>debugLog('info',c,m,d,undefined,t);export const debugWarn=(c:DebugCategory,m:string,d?:Record<string,unknown>,t?:string)=>debugLog('warn',c,m,d,undefined,t);export const debugError=(c:DebugCategory,m:string,d?:Record<string,unknown>,t?:string)=>debugLog('error',c,m,d,undefined,t);export const debugSuccess=(c:DebugCategory,m:string,d?:Record<string,unknown>,ms?:number,t?:string)=>debugLog('success',c,m,d,ms,t)
export const startDebugTrace=(name:string,data?:Record<string,unknown>)=>{const t=tid(),s=performance.now();debugTrace(`TRACE START: ${name}`,data,t);return{traceId:t,end:(m=`TRACE END: ${name}`,d?:Record<string,unknown>)=>{const ms=Math.round(performance.now()-s);debugSuccess('performance',m,d,ms,t);return ms},fail:(e:unknown,d?:Record<string,unknown>)=>{const ms=Math.round(performance.now()-s);debugError('error',`TRACE FAILED: ${name}`,{error:e,...d},t);debugLog('error','performance',`TRACE DURATION: ${name}`,d,ms,t);return ms}}}
const classify=(raw:string)=>{try{const p=new URL(raw,location.origin).pathname;if(p.includes('/rest/v1/rpc/'))return{service:'supabase-rpc',resource:p.split('/rest/v1/rpc/')[1]};if(p.includes('/rest/v1/'))return{service:'supabase-rest',resource:p.split('/rest/v1/')[1]};if(p.includes('/functions/v1/'))return{service:'supabase-function',resource:p.split('/functions/v1/')[1]};if(p.includes('/storage/v1/'))return{service:'supabase-storage',resource:p.split('/storage/v1/')[1]};return{service:'http',resource:p}}catch{return{service:'http',resource:raw.slice(0,160)}}}
const responseSummary=async(r:Response)=>{try{const text=await r.clone().text(),out:Record<string,unknown>={bytes:text.length};if(text)try{const p=JSON.parse(text);out.kind=Array.isArray(p)?'array':typeof p;if(Array.isArray(p))out.count=p.length;if(p&&typeof p==='object'){out.errorCode=p.code;out.errorMessage=p.message||p.error_description;out.hint=p.hint;const rows=Array.isArray(p)?p:[p];const first=rows[0] as Record<string,unknown>|undefined;if(first&&typeof first==='object'){if(first.id)out.entityId=first.id;if(first.status)out.status=first.status;if(first.university)out.university=first.university}}}catch{}return out}catch{return{}}}
const requestBodySummary=async(r:Request)=>{try{const text=await r.clone().text();if(!text)return undefined;const p=JSON.parse(text);if(p&&typeof p==='object'&&!Array.isArray(p)){const o:Record<string,unknown>={};for(const[k,v]of Object.entries(p as Record<string,unknown>))if(!/authorization|apikey|token|password|cookie|secret|access_key|refresh/i.test(k))o[k]=Array.isArray(v)?{type:'array',count:v.length}:typeof v==='string'&&v.length>180?`${v.slice(0,180)}…`:v;return o}return{bodyType:Array.isArray(p)?'array':typeof p}}catch{return undefined}}
const resourceTable=(resource:string)=>resource.split('?')[0].split('/')[0]
let lastListingMutation:{ts:number,id?:unknown,status?:unknown,university?:unknown,requestId:string}|null=null
let lastStorageUpload:{ts:number,path?:unknown,requestId:string}|null=null
export const debugFetch:typeof window.fetch=async(input,init)=>{const s=performance.now(),requestId=tid(),r=new Request(input,init),{service,resource}=classify(r.url);let query:Record<string,string>|undefined;try{query=Object.fromEntries([...new URL(r.url).searchParams.entries()].filter(([k])=>!/(token|key|secret|password)/i.test(k)))}catch{}const body=await requestBodySummary(r);const table=service==='supabase-rest'?resourceTable(resource):undefined;debugTrace(`HTTP ${r.method} ${resource}`,{requestId,service,resource,table,query,body},requestId);try{const f=originalFetch||nativeFetch;if(!f)throw new Error('Fetch unavailable');const res=await f(r),ms=Math.round(performance.now()-s),summary=await responseSummary(res),cat:DebugCategory=service.startsWith('supabase')?'supabase':'network';const op=r.method==='POST'?'insert-or-rpc':r.method==='PATCH'?'update':r.method==='DELETE'?'delete':r.method==='PUT'?'upsert':'select';if(service==='supabase-storage'&&r.method==='POST'&&res.ok){lastStorageUpload={ts:Date.now(),path:resource,requestId};debugSuccess('storage','Storage upload correlated',{requestId,path:resource},ms,requestId)}if(table==='listings'&&body){const previousStatus=lastListingMutation?.id===body.id?lastListingMutation.status:undefined;const listingData={requestId,table,listingId:body.id||body.listing_id||summary.entityId,status:body.status,previousStatus,university:body.university,fields:Object.keys(body)};debugLog(res.ok?'success':'error','supabase',`LISTING DB ${op} ${res.ok?'completed':'failed'}`,listingData,ms,requestId);if(res.ok){lastListingMutation={ts:Date.now(),id:body.id||summary.entityId,status:body.status||summary.status,university:body.university||summary.university,requestId};if(previousStatus&&body.status&&previousStatus!==body.status)debugWarn('supabase','LISTING STATE TRANSITION',{...listingData,from:previousStatus,to:body.status});if(!summary.entityId&&!body.id&&op==='insert-or-rpc')debugWarn('supabase','LISTING INSERT SUCCEEDED WITHOUT ID IN RESPONSE',{requestId,table,body})}else if(lastStorageUpload&&Date.now()-lastStorageUpload.ts<60_000){debugError('error','ROOT-CAUSE CANDIDATE: listing DB failed after recent storage upload',{requestId,listingRequestId:requestId,storageRequestId:lastStorageUpload.requestId,storagePath:lastStorageUpload.path,elapsedMs:Date.now()-lastStorageUpload.ts})}}
if(res.ok)debugSuccess(cat,`HTTP ${res.status} ${r.method} ${resource}`,{requestId,service,resource,table,...summary},ms,requestId);else debugLog('error',cat,`HTTP ${res.status} ${r.method} ${resource}`,{requestId,service,resource,table,...summary},ms,requestId);if(res.ok&&summary.kind==='array'&&summary.count===0)debugWarn('supabase',`SUCCESS BUT ZERO RESULTS: ${resource}`,{requestId,service,resource,table,query});return res}catch(e){const ms=Math.round(performance.now()-s);debugError('network',`HTTP FAILED ${r.method} ${resource}`,{requestId,service,resource,table,error:e},requestId);debugLog('error','performance',`HTTP DURATION ${r.method} ${resource}`,{},ms,requestId);throw e}}
export const subscribeDebugger=(fn:(e:DebugEvent[])=>void)=>{listeners.add(fn);fn([...events]);return()=>{listeners.delete(fn)}};export const getDebugEvents=()=>[...events];export const clearDebugEvents=()=>{events=[];persist();notify()};export const setDebugPaused=(v:boolean)=>{paused=v;if(!v)debugInfo('app','Debugger resumed')};export const isDebugPaused=()=>paused
export const addDebugBreadcrumb=(message:string,data?:Record<string,unknown>)=>debugInfo('app',`BREADCRUMB: ${message}`,data)
export const exportDebugBundle=()=>{const payload={exportedAt:new Date().toISOString(),app:'CampusPlug',url:location.href.split('?')[0],userAgent:navigator.userAgent,online:navigator.onLine,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},events:getDebugEvents()};const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`campusplug-debug-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;a.click();URL.revokeObjectURL(u)}
export const getDebuggerStats=()=>{const c=events.reduce((a,e)=>(a[e.level]=(a[e.level]||0)+1,a),{} as Record<string,number>);return{total:events.length,errors:c.error||0,warnings:c.warn||0,traces:c.trace||0,lastEvent:events.at(-1)?.ts||null}}
export const installRuntimeDebugger=()=>{if(initialized||typeof window==='undefined')return;initialized=true;try{const x=localStorage.getItem(KEY);if(x){const p=JSON.parse(x);if(Array.isArray(p))events=p.slice(-MAX)}}catch{}originalConsole={error:console.error,warn:console.warn};console.error=(...a)=>{debugError('error','console.error',{args:a.map(safe)});originalConsole.error?.(...a)};console.warn=(...a)=>{debugWarn('app','console.warn',{args:a.map(safe)});originalConsole.warn?.(...a)};originalFetch=window.fetch.bind(window);window.fetch=debugFetch;const storageMutator=(storage:Storage,name:string)=>{const methods=['setItem','removeItem','clear'] as const;for(const method of methods){const original=(storage[method] as (...args:unknown[])=>unknown).bind(storage);storage[method]=((...args:unknown[])=>{const before=storage.length;const result=original(...args);debugInfo('storage',`${name}.${method}`,{key:typeof args[0]==='string'?args[0]:undefined,changed:method==='clear'?'all':method==='removeItem'?args[0]:'value-updated',sizeBefore:before,sizeAfter:storage.length});return result}) as never}};try{storageMutator(localStorage,'localStorage');storageMutator(sessionStorage,'sessionStorage')}catch{}window.addEventListener('error',e=>debugError('error','window.error',{message:e.message,filename:e.filename,line:e.lineno,column:e.colno,error:e.error}));window.addEventListener('unhandledrejection',e=>debugError('error','unhandledrejection',{reason:e.reason}));window.addEventListener('online',()=>debugSuccess('network','Browser is online'));window.addEventListener('offline',()=>debugWarn('network','Browser went offline'));window.addEventListener('pagehide',()=>debugInfo('navigation','Page hidden'));window.addEventListener('pageshow',e=>debugInfo('navigation','Page shown',{persisted:e.persisted}));window.addEventListener('popstate',()=>debugInfo('navigation','History navigation',{path:location.pathname}));const push=history.pushState;history.pushState=function(...a){const x=push.apply(this,a);debugInfo('navigation','pushState',{path:location.pathname});return x};const replace=history.replaceState;history.replaceState=function(...a){const x=replace.apply(this,a);debugInfo('navigation','replaceState',{path:location.pathname});return x};debugSuccess('app','Runtime debugger initialized',{version:'2.1.2',maxEvents:MAX})}
