export type LocalTransactionStatus = 'draft' | 'queued' | 'syncing' | 'failed' | 'synced'
export type LocalTransaction = { id:string; ownerId:string; kind:string; payload:unknown; status:LocalTransactionStatus; updatedAt:number; error?:string }

const DB_NAME='campus-plug-local-state'; const STORE='transactions'; const VERSION=2
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(typeof indexedDB==='undefined'){reject(new Error('IndexedDB unavailable'));return};const request=indexedDB.open(DB_NAME,VERSION);request.onupgradeneeded=()=>{const db=request.result;let store:IDBObjectStore;if(!db.objectStoreNames.contains(STORE)){store=db.createObjectStore(STORE,{keyPath:'id'})}else{store=request.transaction!.objectStore(STORE)}if(!store.indexNames.contains('ownerId'))store.createIndex('ownerId','ownerId',{unique:false})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error('Unable to open local state'))})}

export async function purgeStaleLocalTransactions(activeUserId:string){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');const store=tx.objectStore(STORE);const request=store.getAll();request.onsuccess=()=>{for(const value of request.result as Array<Partial<LocalTransaction>>){if(value.ownerId!==activeUserId)store.delete(value.id)};tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error('Unable to purge stale local state'))};request.onerror=()=>reject(request.error||new Error('Unable to inspect local state'))});db.close()}

export async function saveLocalTransaction(tx:LocalTransaction){const db=await openDb();await new Promise<void>((resolve,reject)=>{const req=db.transaction(STORE,'readwrite').objectStore(STORE).put(tx);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)});db.close()}
export async function getLocalTransaction(id:string){const db=await openDb();const value=await new Promise<LocalTransaction|undefined>((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});db.close();return value}
export async function listActiveLocalTransactions(ownerId?:string){const db=await openDb();const values=await new Promise<LocalTransaction[]>((resolve,reject)=>{const req=db.transaction(STORE,'readonly').objectStore(STORE).getAll();req.onsuccess=()=>resolve((req.result||[]).filter((tx:LocalTransaction)=>tx.status!=='synced'&&(!ownerId||tx.ownerId===ownerId)));req.onerror=()=>reject(req.error)});db.close();return values}
export async function removeLocalTransaction(id:string){const db=await openDb();await new Promise<void>((resolve,reject)=>{const req=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);req.onsuccess=()=>resolve();req.onerror=()=>reject(req.error)});db.close()}
