import { useMemo, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Activity, AlertTriangle, CreditCard, Database, LayoutDashboard, RefreshCw, Search, Shield, Users, WalletCards } from 'lucide-react'
import toast from 'react-hot-toast'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/contexts/AuthContext'
import TransactionTimeline from '@/components/admin/TransactionTimeline'

const tabs=[['overview','Overview',LayoutDashboard],['transactions','Transactions',CreditCard],['payments','Payments',WalletCards],['security','Security',Shield],['operations','Operations',Activity]]

export default function AdminConsole(){
  const { profile }=useAuth(); const [tab,setTab]=useState('overview'); const [transactionId,setTransactionId]=useState('')
  const isAdmin=profile?.badges?.includes('Plug Dev') || profile?.badges?.includes('Community Hero')
  const {data:snapshot,isLoading,isError,refetch}=useQuery({
    queryKey:['admin-console-snapshot'], enabled:isAdmin,
    queryFn:async()=>{const {data,error}=await supabase.rpc('get_admin_console_snapshot');if(error)throw error;return data},
    staleTime:15_000,
  })
  const cards=useMemo(()=>snapshot?[
    ['Users',snapshot.users,Users],['Active listings',snapshot.active_listings,Database],['30d transactions',snapshot.transactions_30d,CreditCard],
    ['Disputed',snapshot.disputed,AlertTriangle],['Payment events 24h',snapshot.payment_events_24h,WalletCards],['Errors 24h',snapshot.observability_errors_24h,Activity]
  ]:[],[snapshot])
  if(!isAdmin)return <main className="page-shell"><div className="surface p-8 text-center"><Shield className="mx-auto mb-3 text-[var(--md-error)]"/><h1 className="text-xl font-black">Admin access required</h1><p className="mt-2 text-sm text-white/40">This console is restricted to platform operators.</p></div></main>
  return <main className="page-shell space-y-6">
    <header className="page-header"><div><p className="section-label">Operations</p><h1 className="page-title">Admin Console</h1><p className="page-subtitle">System health, marketplace activity, payments, security and audit trails in one command center.</p></div><button className="btn-secondary text-sm" onClick={()=>refetch()} disabled={isLoading}><RefreshCw size={15} className={isLoading?'animate-spin':''}/> Refresh</button></header>
    <nav className="flex gap-2 overflow-x-auto pb-1" aria-label="Admin sections">{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} aria-current={tab===id?'page':undefined} className={`flex min-h-11 shrink-0 items-center gap-2 rounded-full border px-4 text-sm font-bold ${tab===id?'border-primary/40 bg-primary/10 text-primary':'border-[var(--md-outline-variant)] text-white/45 hover:text-white'}`}><Icon size={14}/>{label}</button>)}</nav>
    {isError&&<div className="surface p-4 border-[var(--md-error)]/40 text-sm text-[var(--md-error)]" role="alert">Admin data is temporarily unavailable. Refresh and try again.</div>}
    {tab==='overview'&&<><div className="grid grid-cols-2 gap-3 md:grid-cols-3">{cards.map(([label,value,Icon])=><div key={label} className="stat-card"><Icon size={16} className="text-primary mb-3"/><div className="text-2xl font-black">{value??'—'}</div><div className="text-xs text-white/40 mt-1">{label}</div></div>)}</div><div className="grid gap-5 lg:grid-cols-2"><section className="surface p-5"><h2 className="font-black">Operational health</h2><div className="mt-4 space-y-3"><HealthRow label="Payment processing" value={snapshot?.payment_failures_24h||0} bad={snapshot?.payment_failures_24h>0}/><HealthRow label="Observability errors" value={snapshot?.observability_errors_24h||0} bad={snapshot?.observability_errors_24h>0}/><HealthRow label="Ledger activity" value={snapshot?.ledger_entries_24h||0}/></div></section><section className="surface p-5"><h2 className="font-black">Recent errors</h2><div className="mt-4 space-y-2">{(snapshot?.recent_errors||[]).slice(0,6).map((e,i)=><div key={e.id||i} className="rounded-xl border border-[var(--md-outline-variant)] p-3"><div className="flex justify-between gap-3 text-xs font-bold"><span>{e.service} · {e.operation}</span><span className="text-white/30">{new Date(e.created_at).toLocaleTimeString()}</span></div><div className="mt-1 text-[11px] text-[var(--md-error)]">{e.error_code||'runtime_error'}</div></div>)}{!snapshot?.recent_errors?.length&&<Empty text="No recent errors recorded."/>}</div></section></div></>}
    {tab==='transactions'&&<section className="space-y-5"><div className="surface p-5"><label className="label" htmlFor="admin-tx-id">Transaction ID</label><div className="flex gap-2"><input id="admin-tx-id" className="input" value={transactionId} onChange={e=>setTransactionId(e.target.value.trim())} placeholder="Paste a transaction UUID"/><button className="btn-primary shrink-0" onClick={()=>{if(!transactionId)toast.error('Enter a transaction ID')}}><Search size={15}/> Inspect</button></div></div><TransactionTimeline transactionId={transactionId} admin={isAdmin}/></section>}
    {tab==='payments'&&<section className="surface overflow-hidden"><div className="p-5 border-b border-[var(--md-outline-variant)]"><h2 className="font-black">Payment event ledger</h2><p className="text-xs text-white/40 mt-1">Provider events are immutable; this view is read-only.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-[var(--md-outline-variant)]"><th className="p-4">Event</th><th className="p-4">Reference</th><th className="p-4">Status</th><th className="p-4">Received</th></tr></thead><tbody>{(snapshot?.recent_payments||[]).map((e,i)=><tr key={e.event_id||i} className="border-b border-[var(--md-outline-variant)]"><td className="p-4 font-bold">{e.event_type}</td><td className="p-4 font-mono text-white/50">{e.reference||'—'}</td><td className="p-4">{e.processing_status}</td><td className="p-4 text-white/40">{new Date(e.received_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>}
    {tab==='security'&&<section className="grid gap-5 md:grid-cols-2"><div className="surface p-5"><h2 className="font-black">Security posture</h2><ul className="mt-4 space-y-3 text-sm text-white/55"><li>✓ Platform-admin RPC authorization</li><li>✓ Service-role-only sensitive telemetry tables</li><li>✓ Transaction transition audit trail</li><li>✓ Payment event idempotency ledger</li><li>✓ Client device signals are not authentication</li></ul></div><div className="surface p-5"><h2 className="font-black">Incident signals</h2><div className="mt-4 text-3xl font-black">{snapshot?.observability_errors_24h||0}</div><p className="text-xs text-white/40">observability errors in the last 24 hours</p></div></section>}
    {tab==='operations'&&<section className="grid gap-5 md:grid-cols-2"><div className="surface p-5"><h2 className="font-black">Marketplace</h2><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span className="text-white/45">Active listings</span><strong>{snapshot?.active_listings??'—'}</strong></div><div className="flex justify-between"><span className="text-white/45">Pending/review</span><strong>{snapshot?.pending_listings??'—'}</strong></div></div></div><div className="surface p-5"><h2 className="font-black">Users</h2><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span className="text-white/45">Total</span><strong>{snapshot?.users??'—'}</strong></div><div className="flex justify-between"><span className="text-white/45">Verified</span><strong>{snapshot?.verified_users??'—'}</strong></div></div></div></section>}
  </main>
}
function HealthRow({label,value,bad}){return <div className="flex items-center justify-between rounded-xl border border-[var(--md-outline-variant)] p-3"><span className="text-sm text-white/55">{label}</span><span className={`font-mono font-black ${bad?'text-[var(--md-error)]':'text-primary'}`}>{value}</span></div>}
function Empty({text}){return <div className="py-8 text-center text-sm text-white/30">{text}</div>}