import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { Bell, BookOpen, Bot, Bus, FileText, GraduationCap, MapPin, MessageCircle, Plus, Send, Sparkles, Users, X, Zap } from 'lucide-react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { supabase } from '@/lib/supabase'
import { useAuth } from '@/contexts/AuthContext'
import { ReferralCard } from '@/components/ui/Referral'
import { ThemeToggle } from '@/components/ui/ThemeToggle'
import toast from 'react-hot-toast'

const TABS = [
  ['community', 'Community', Users],
  ['classes', 'Classes', GraduationCap],
  ['notes', 'Notes', FileText],
  ['places', 'Campus map', MapPin],
  ['skills', 'Skills', Zap],
  ['rewards', 'Rewards', Sparkles],
] as const

function externalMapsUrl(name: string, university: string) {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${name}, ${university}`)}`
}

function boltUrl(name: string, university: string) {
  return `https://bolt.eu/cities/lagos/` + `?destination=${encodeURIComponent(`${name}, ${university}`)}`
}

export default function CampusHub() {
  const { profile, user } = useAuth()
  const [tab, setTab] = useState<(typeof TABS)[number][0]>('community')
  return (
    <div className="content-width page-gutter py-6 sm:py-8">
      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <p className="section-label">Campus Plug OS</p>
          <h1 className="text-3xl font-black tracking-tight">Campus Hub</h1>
          <p className="mt-1 max-w-2xl text-sm text-white/45">Classes, people, notes, campus places, skills and rewards — in one student layer.</p>
        </div>
        <div className="flex items-center gap-2"><ThemeToggle /><Link to="/chat" className="btn-secondary"><MessageCircle size={15}/> Messages</Link></div>
      </div>
      <div className="mb-6 flex gap-2 overflow-x-auto pb-1">
        {TABS.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`flex min-h-10 shrink-0 items-center gap-2 rounded-xl border px-3 text-xs font-bold transition-all ${tab === id ? 'border-cyan/40 bg-cyan/10 text-cyan' : 'border-white/10 bg-white/[.03] text-white/45 hover:text-white'}`}><Icon size={14}/>{label}</button>)}
      </div>
      <AnimatePresence mode="wait">
        <motion.div key={tab} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:.18}}>
          {tab === 'community' && <Community university={profile?.university || ''} userId={user?.id || ''}/>} 
          {tab === 'classes' && <Classes university={profile?.university || ''} userId={user?.id || ''}/>} 
          {tab === 'notes' && <Notes university={profile?.university || ''} userId={user?.id || ''}/>} 
          {tab === 'places' && <Places university={profile?.university || ''} userId={user?.id || ''}/>} 
          {tab === 'skills' && <Skills/>}
          {tab === 'rewards' && <ReferralCard profile={profile}/>} 
        </motion.div>
      </AnimatePresence>
    </div>
  )
}

function Community({ university, userId }: { university: string; userId: string }) {
  const qc = useQueryClient(); const [selected, setSelected] = useState<any>(null); const [text, setText] = useState(''); const [showCreate, setShowCreate] = useState(false); const [name, setName] = useState(''); const [course, setCourse] = useState('')
  const { data: groups = [] } = useQuery({ queryKey:['groups',university], enabled:!!university, queryFn: async()=>{ const {data,error}=await supabase.from('group_chats').select('*').eq('university',university).eq('is_archived',false).order('last_activity_at',{ascending:false}); if(error) throw error; return data||[] }})
  const { data: members = [] } = useQuery({queryKey:['group-members',selected?.id],enabled:!!selected?.id,queryFn:async()=>{const {data,error}=await supabase.from('group_chat_members').select('user_id').eq('group_id',selected.id);if(error)throw error;return data||[]}})
  const { data: messages = [] } = useQuery({queryKey:['group-messages',selected?.id],enabled:!!selected?.id,queryFn:async()=>{const {data,error}=await supabase.from('group_chat_messages').select('*, profiles:sender_id(full_name)').eq('group_id',selected.id).order('created_at',{ascending:true}).limit(100);if(error)throw error;return data||[]}})
  useEffect(()=>{ if(!selected?.id)return; const c=supabase.channel(`group:${selected.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'group_chat_messages',filter:`group_id=eq.${selected.id}`},()=>qc.invalidateQueries({queryKey:['group-messages',selected.id]})).subscribe(); return()=>{supabase.removeChannel(c)} },[selected?.id,qc])
  const join=async(g:any)=>{const {error}=await supabase.from('group_chat_members').upsert({group_id:g.id,user_id:userId});if(error)toast.error(error.message);else{setSelected(g);toast.success('Joined the study group')}}
  const send=async(body=text,type='text',metadata={})=>{if(!body.trim()||!selected)return;const {error}=await supabase.from('group_chat_messages').insert({group_id:selected.id,sender_id:userId,body:body.trim(),message_type:type,metadata});if(error)toast.error(error.message);else{setText('');qc.invalidateQueries({queryKey:['group-messages',selected.id]})}}
  const create=async()=>{if(!name.trim()||!university)return;const {data,error}=await supabase.from('group_chats').insert({name:name.trim(),course_code:course.trim()||null,university,creator_id:userId}).select().single();if(error)toast.error(error.message);else{await supabase.from('group_chat_members').insert({group_id:data.id,user_id:userId,role:'owner'});setName('');setCourse('');setShowCreate(false);setSelected(data);qc.invalidateQueries({queryKey:['groups',university]});toast.success('Group created')}}
  return <div className="grid gap-4 lg:grid-cols-[320px_1fr]">
    <div className="surface p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-bold">Study groups</h2><p className="text-xs text-white/35">Keep the room alive.</p></div><button className="icon-button" onClick={()=>setShowCreate(true)}><Plus size={16}/></button></div><div className="space-y-2">{groups.map((g:any)=><button key={g.id} onClick={()=>join(g)} className={`w-full rounded-xl border p-3 text-left transition ${selected?.id===g.id?'border-cyan/30 bg-cyan/5':'border-white/5 bg-white/[.02] hover:border-white/10'}`}><div className="font-semibold text-sm">{g.name}</div><div className="mt-1 text-xs text-white/35">{g.course_code || 'General'} · {new Date(g.last_activity_at).toLocaleDateString()}</div></button>)}{groups.length===0&&<div className="py-8 text-center text-sm text-white/30">No groups yet. Start one.</div>}</div></div>
    <div className="surface min-h-[520px] p-4">{selected?<><div className="mb-4 flex items-center justify-between border-b border-white/5 pb-3"><div><h2 className="font-bold">{selected.name}</h2><p className="text-xs text-white/35">{members.length} members · prompts, polls and resources keep things moving</p></div><div className="flex gap-1"><button className="tag tag-purple" onClick={()=>send('What are you studying right now?','prompt')}>Prompt</button><button className="tag tag-green" onClick={()=>send('🔥 10-minute challenge: explain one concept without notes.','announcement')}>Challenge</button></div></div><div className="mb-4 h-[360px] space-y-2 overflow-y-auto pr-1">{messages.map((m:any)=><div key={m.id} className={`max-w-[82%] rounded-2xl border px-3 py-2 ${m.sender_id===userId?'ml-auto border-cyan/20 bg-cyan/10':'border-white/5 bg-white/[.03]'}`}><div className="mb-1 text-[10px] font-bold text-white/35">{m.profiles?.full_name||'Student'} · {m.message_type}</div><div className="text-sm text-white/80">{m.body}</div></div>)}{messages.length===0&&<div className="flex h-full items-center justify-center text-sm text-white/25">Say something useful. Or chaotic. Preferably useful.</div>}</div><div className="flex gap-2"><input className="input" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Message the group…"/><button className="btn-primary" onClick={()=>send()}><Send size={15}/></button></div></>:<div className="flex h-full min-h-[480px] items-center justify-center text-center"><div><Users className="mx-auto mb-3 text-cyan"/><h2 className="font-bold">Pick a group</h2><p className="mt-1 text-sm text-white/35">Join a course room and turn dead group chats into useful ones.</p></div></div>}</div>
    {showCreate&&<div className="modal-backdrop"><div className="absolute inset-0" onClick={()=>setShowCreate(false)}/><div className="modal-panel"><div className="modal-header"><h2 className="font-bold">Create study group</h2><button className="icon-button" onClick={()=>setShowCreate(false)}><X size={16}/></button></div><div className="space-y-4 p-5"><input className="input" placeholder="Group name" value={name} onChange={e=>setName(e.target.value)}/><input className="input" placeholder="Course code (optional)" value={course} onChange={e=>setCourse(e.target.value)}/><button className="btn-primary w-full" onClick={create}>Create group</button></div></div></div>}
  </div>
}

function Classes({ university, userId }: { university:string; userId:string }) {
  const qc=useQueryClient(); const [show,setShow]=useState(false); const [course,setCourse]=useState(''); const [title,setTitle]=useState(''); const [details,setDetails]=useState(''); const [materials,setMaterials]=useState('')
  const {data:alerts=[]}=useQuery({queryKey:['class-alerts',university],enabled:!!university,queryFn:async()=>{const {data,error}=await supabase.from('class_alerts').select('*').eq('university',university).order('alert_time',{ascending:true}).limit(50);if(error)throw error;return data||[]}})
  const create=async()=>{const {error}=await supabase.from('class_alerts').insert({course_code:course,title:title||`${course} class`,description:details,materials_needed:materials.split(',').map(x=>x.trim()).filter(Boolean),alert_time:new Date(Date.now()+3600000).toISOString(),created_by:userId,university});if(error)toast.error(error.message);else{setShow(false);setCourse('');setTitle('');setDetails('');setMaterials('');qc.invalidateQueries({queryKey:['class-alerts',university]});toast.success('Class alert sent')}}
  return <div className="space-y-4"><div className="surface flex items-center justify-between p-5"><div><h2 className="font-bold">Class & program alerts</h2><p className="text-sm text-white/40">Send time, venue, details and what students need to bring.</p></div><button className="btn-primary" onClick={()=>setShow(true)}><Bell size={15}/> Send alert</button></div><div className="grid gap-3">{alerts.map((a:any)=><div key={a.id} className="surface p-4"><div className="flex items-start justify-between gap-3"><div><span className="tag tag-purple">{a.course_code}</span><h3 className="mt-2 font-bold">{a.title}</h3><p className="mt-1 text-sm text-white/45">{a.description}</p></div><Bell size={16} className="text-cyan"/></div>{Array.isArray(a.materials_needed)&&a.materials_needed.length>0&&<div className="mt-3 flex flex-wrap gap-2">{a.materials_needed.map((m:string)=><Link key={m} to={`/marketplace?search=${encodeURIComponent(m)}`} className="tag tag-green hover:brightness-125">Buy/rent {m}</Link>)}</div>}<div className="mt-3 text-xs text-white/30">{new Date(a.alert_time).toLocaleString()}</div></div>)}</div>{show&&<div className="modal-backdrop"><div className="absolute inset-0" onClick={()=>setShow(false)}/><div className="modal-panel"><div className="modal-header"><h2 className="font-bold">Send class alert</h2><button className="icon-button" onClick={()=>setShow(false)}><X size={16}/></button></div><div className="space-y-4 p-5"><input className="input" placeholder="Course code" value={course} onChange={e=>setCourse(e.target.value)}/><input className="input" placeholder="Alert title" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="input" rows={3} placeholder="Details, venue, lecturer, timing…" value={details} onChange={e=>setDetails(e.target.value)}/><input className="input" placeholder="Materials, comma separated" value={materials} onChange={e=>setMaterials(e.target.value)}/><button className="btn-primary w-full" onClick={create}>Broadcast alert</button></div></div></div>}</div>
}

function Notes({ university, userId }: { university:string; userId:string }) { const qc=useQueryClient(); const [course,setCourse]=useState(''); const [title,setTitle]=useState(''); const [url,setUrl]=useState(''); const {data:notes=[]}=useQuery({queryKey:['notes',university],enabled:!!university,queryFn:async()=>{const {data,error}=await supabase.from('study_notes').select('*, profiles:uploader_id(full_name)').eq('university',university).eq('is_public',true).order('created_at',{ascending:false});if(error)throw error;return data||[]}}); const add=async()=>{const {error}=await supabase.from('study_notes').insert({uploader_id:userId,university,course_code:course,title,file_url:url||null,is_public:true});if(error)toast.error(error.message);else{setCourse('');setTitle('');setUrl('');qc.invalidateQueries({queryKey:['notes',university]});toast.success('Note shared')}}; return <div className="grid gap-4 lg:grid-cols-[360px_1fr]"><div className="surface p-5"><h2 className="font-bold">Share notes</h2><p className="mt-1 text-xs text-white/35">Share links to PDFs, documents or useful resources.</p><div className="mt-4 space-y-3"><input className="input" placeholder="Course code" value={course} onChange={e=>setCourse(e.target.value)}/><input className="input" placeholder="Note title" value={title} onChange={e=>setTitle(e.target.value)}/><input className="input" placeholder="File URL" value={url} onChange={e=>setUrl(e.target.value)}/><button className="btn-primary w-full" onClick={add}><BookOpen size={15}/> Share note</button></div></div><div className="space-y-3">{notes.map((n:any)=><a key={n.id} href={n.file_url||'#'} target="_blank" rel="noreferrer" className="surface surface-interactive block p-4"><div className="flex items-center justify-between"><span className="tag tag-purple">{n.course_code}</span><FileText size={16} className="text-cyan"/></div><h3 className="mt-3 font-bold">{n.title}</h3><p className="mt-1 text-xs text-white/35">Shared by {n.profiles?.full_name||'student'} · {new Date(n.created_at).toLocaleDateString()}</p></a>)}{notes.length===0&&<div className="surface p-10 text-center text-white/30">No shared notes yet.</div>}</div></div> }

function Places({ university, userId }: { university:string; userId:string }) { const qc=useQueryClient(); const [name,setName]=useState(''); const [type,setType]=useState('department'); const [coords,setCoords]=useState(''); const {data:places=[]}=useQuery({queryKey:['campus-places',university],enabled:!!university,queryFn:async()=>{const {data,error}=await supabase.from('campus_locations').select('*').eq('university',university).order('name');if(error)throw error;return data||[]}}); const add=async()=>{const [lat,lng]=coords.split(',').map(Number); if(!name||!Number.isFinite(lat)||!Number.isFinite(lng))return toast.error('Add name and coordinates as lat,lng');const {error}=await supabase.from('campus_locations').insert({name,university,location_type:type,coordinates:{lat,lng},created_by:userId});if(error)toast.error(error.message);else{setName('');setCoords('');qc.invalidateQueries({queryKey:['campus-places',university]});toast.success('Place suggestion added')}}; return <div className="space-y-4"><div className="surface p-5"><h2 className="font-bold">Campus navigation layer</h2><p className="mt-1 text-sm text-white/40">Departments, offices, lecture halls and useful places can become shared navigation points.</p><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_160px_180px_auto]"><input className="input" placeholder="Place name" value={name} onChange={e=>setName(e.target.value)}/><select className="input" value={type} onChange={e=>setType(e.target.value)}><option>department</option><option>office</option><option>lecture_hall</option><option>library</option><option>other</option></select><input className="input" placeholder="lat, lng" value={coords} onChange={e=>setCoords(e.target.value)}/><button className="btn-primary" onClick={add}>Suggest</button></div></div><div className="grid gap-3 sm:grid-cols-2">{places.map((p:any)=>{const c=p.coordinates||{};return <div key={p.id} className="surface p-4"><div className="flex items-start justify-between"><div><span className="tag tag-purple">{p.location_type}</span><h3 className="mt-2 font-bold">{p.name}</h3><p className="mt-1 text-xs text-white/35">{p.description||'Campus location'}</p></div><MapPin className="text-cyan" size={17}/></div><div className="mt-4 flex gap-2"><a className="btn-secondary flex-1 justify-center" target="_blank" rel="noreferrer" href={externalMapsUrl(p.name,university)}>Google Maps</a><a className="btn-secondary flex-1 justify-center" target="_blank" rel="noreferrer" href={boltUrl(p.name,university)}><Bus size={14}/> Bolt</a></div><div className="mt-2 text-[10px] text-white/20">{c.lat},{c.lng}</div></div>})}</div></div> }

function Skills() { return <div className="surface p-6"><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-purple/10 text-purple"><Zap/></div><div><h2 className="text-xl font-black">Rent a skill, not just an item</h2><p className="mt-1 max-w-xl text-sm text-white/45">Campus Plug already has the student-services marketplace and gig booking foundation. Use it for tutoring, design, repairs, writing, errands and other time-based help.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{['Tutoring','Tech & repairs','Design & creative'].map(x=><Link key={x} to={`/gigs?category=${encodeURIComponent(x)}`} className="surface-interactive rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="font-bold">{x}</div><div className="mt-1 text-xs text-white/35">Browse available student skills →</div></Link>)}</div></div> }
