import { useSearchParams } from 'react-router-dom'
import { FileText, MessageSquare, Laptop, ExternalLink } from 'lucide-react'
import { useAuth } from '@/contexts/AuthContext'
import MarketplaceChat from '@/components/chat/MarketplaceChat'

export default function DesktopWorkspace(){
  const {user}=useAuth();const [params]=useSearchParams();const fileUrl=params.get('file');const otherUserId=params.get('other');const transactionId=params.get('tx')
  return <main className="max-w-[1500px] mx-auto px-4 py-6"><div className="flex items-center gap-3 mb-5"><div className="w-10 h-10 rounded-xl bg-cyan/10 border border-cyan/20 flex items-center justify-center"><Laptop className="text-cyan" size={20}/></div><div><div className="text-[10px] uppercase tracking-[.2em] text-cyan font-black">Laptop Workspace</div><h1 className="text-2xl font-black">Marketplace command desk</h1></div></div><div className="grid lg:grid-cols-[1.55fr_1fr] gap-5 min-h-[72vh]"><section className="bg-obsidian-400 border border-obsidian-500 rounded-2xl overflow-hidden flex flex-col"><div className="px-5 py-4 border-b border-obsidian-500 flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-black"><FileText size={16} className="text-cyan"/>Study guide / document preview</div>{fileUrl&&<a href={fileUrl} target="_blank" rel="noreferrer" className="text-xs text-white/40 hover:text-cyan flex items-center gap-1">Open file <ExternalLink size={12}/></a>}</div><div className="flex-1 min-h-[560px] bg-black/30">{fileUrl?<iframe title="Document preview" src={fileUrl} className="w-full h-full min-h-[560px] border-0"/>:<div className="h-full min-h-[560px] flex items-center justify-center p-8 text-center"><div><FileText size={42} className="mx-auto text-white/20 mb-3"/><div className="font-black">Select a study document</div><p className="text-xs text-white/35 mt-2 max-w-sm">Open the workspace with a document URL to keep multi-page notes visible beside your transaction chat.</p></div></div>}</div></section><section className="bg-obsidian-400 border border-obsidian-500 rounded-2xl overflow-hidden flex flex-col"><div className="px-5 py-4 border-b border-obsidian-500 flex items-center gap-2 text-sm font-black"><MessageSquare size={16} className="text-plug-green"/>Buyer / seller chat</div><div className="flex-1 min-h-[560px]">{user&&otherUserId?<MarketplaceChat currentUserId={user.id} otherUserId={otherUserId} transactionId={transactionId||undefined}/>:<div className="h-full min-h-[560px] flex items-center justify-center p-8 text-center text-white/35"><div><MessageSquare size={38} className="mx-auto text-white/20 mb-3"/><div className="font-black text-white/70">Chat context ready</div><p className="text-xs mt-2 max-w-xs">Open the workspace from a listing or transaction so the correct buyer/seller thread is attached.</p></div></div>}</div></section></div></main>
}
