import { useEffect, useMemo, useState } from 'react'
import { Bug, Download, Trash2, Pause, Play, Search, X, AlertTriangle, CheckCircle2, Activity } from 'lucide-react'
import { clearDebugEvents, exportDebugBundle, getDebuggerStats, installRuntimeDebugger, isDebugPaused, setDebugPaused, subscribeDebugger } from '@/lib/debugger'
import type { DebugEvent } from '@/lib/debugger'

const levelClass:Record<string,string>={error:'text-red-300 bg-red-500/10 border-red-500/20',warn:'text-amber-300 bg-amber-500/10 border-amber-500/20',success:'text-emerald-300 bg-emerald-500/10 border-emerald-500/20',trace:'text-cyan-300 bg-cyan-500/5 border-cyan-500/10',info:'text-white/70 bg-white/[.03] border-white/10'}
const buttonClass='w-9 h-9 rounded-lg border border-white/10 bg-white/[.03] text-white/50 hover:text-white hover:border-cyan/30 flex items-center justify-center transition-colors'
const labelClass='text-[9px] font-black uppercase tracking-[.2em] text-white/25 mb-1'

export default function RuntimeDebugger(){
  const [open,setOpen]=useState(false),[events,setEvents]=useState<DebugEvent[]>([]),[filter,setFilter]=useState(''),[level,setLevel]=useState('all'),[selected,setSelected]=useState<DebugEvent|null>(null),[paused,setPaused]=useState(isDebugPaused())
  useEffect(()=>{installRuntimeDebugger();return subscribeDebugger(setEvents)},[])
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='d'){e.preventDefault();setOpen(v=>!v)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[])
  const stats=useMemo(()=>getDebuggerStats(),[events])
  const visible=useMemo(()=>events.filter(e=>(level==='all'||e.level===level)&&(!filter||`${e.message} ${e.category} ${JSON.stringify(e.data||{})}`.toLowerCase().includes(filter.toLowerCase()))).slice().reverse(),[events,filter,level])
  if(!open)return <button onClick={()=>setOpen(true)} title="Runtime debugger (Ctrl+Shift+D)" className="fixed bottom-4 right-4 z-[100] w-11 h-11 rounded-full border border-cyan/30 bg-obsidian-950/90 backdrop-blur-xl text-cyan shadow-2xl flex items-center justify-center hover:scale-105 transition-transform"><Bug size={19}/>{stats.errors>0&&<span className="absolute -top-1 -right-1 min-w-4 h-4 px-1 rounded-full bg-red-500 text-[9px] font-black text-white flex items-center justify-center">{stats.errors>99?'99+':stats.errors}</span>}</button>
  return <div className="fixed inset-0 z-[200] bg-black/70 backdrop-blur-sm p-2 sm:p-5" onClick={e=>e.target===e.currentTarget&&setOpen(false)}>
    <section className="h-full max-w-7xl mx-auto rounded-2xl overflow-hidden border border-white/10 bg-obsidian-950 shadow-2xl flex flex-col text-white">
      <header className="shrink-0 border-b border-white/10 px-4 py-3 flex flex-wrap items-center gap-3 bg-obsidian-900/95">
        <div className="flex items-center gap-2"><div className="w-9 h-9 rounded-xl bg-cyan/10 border border-cyan/20 flex items-center justify-center text-cyan"><Bug size={18}/></div><div><div className="font-black tracking-tight">Runtime Debugger</div><div className="text-[10px] uppercase tracking-widest text-white/30">CampusPlug diagnostic console</div></div></div>
        <div className="flex gap-2 ml-auto text-[11px] font-mono"><span className="px-2 py-1 rounded-lg border border-white/10 bg-white/[.03]">{stats.total} events</span><span className="px-2 py-1 rounded-lg border border-red-500/20 text-red-300">{stats.errors} errors</span><span className="px-2 py-1 rounded-lg border border-amber-500/20 text-amber-300">{stats.warnings} warnings</span></div>
        <div className="flex items-center gap-1 w-full sm:w-auto"><button onClick={()=>{const v=!paused;setPaused(v);setDebugPaused(v)}} className={buttonClass} title={paused?'Resume':'Pause'}>{paused?<Play size={15}/>:<Pause size={15}/>}</button><button onClick={exportDebugBundle} className={buttonClass} title="Export diagnostic bundle"><Download size={15}/></button><button onClick={()=>{if(confirm('Clear all debugger events?'))clearDebugEvents()}} className={buttonClass} title="Clear logs"><Trash2 size={15}/></button><button onClick={()=>setOpen(false)} className={buttonClass} title="Close"><X size={16}/></button></div>
      </header>
      <div className="shrink-0 border-b border-white/10 px-4 py-3 flex flex-wrap gap-2"><div className="relative flex-1 min-w-[220px]"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-white/30"/><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Search messages, categories, metadata…" className="w-full h-9 rounded-lg border border-white/10 bg-white/[.03] pl-9 pr-3 text-xs outline-none focus:border-cyan/40"/></div>{['all','error','warn','success','info','trace'].map(x=><button key={x} onClick={()=>setLevel(x)} className={`px-3 h-9 rounded-lg border text-[11px] font-bold capitalize ${level===x?'border-cyan/40 bg-cyan/10 text-cyan':'border-white/10 text-white/40'}`}>{x}</button>)}</div>
      <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_minmax(320px,40%)] min-h-0 flex-1">
        <div className="min-h-0 overflow-auto divide-y divide-white/[.05]">{visible.length===0?<div className="h-full flex items-center justify-center text-white/25 text-sm"><Activity size={18} className="mr-2"/>No matching events</div>:visible.map(e=><button key={e.id} onClick={()=>setSelected(e)} className="w-full text-left px-4 py-3 hover:bg-white/[.03] transition-colors grid grid-cols-[80px_62px_1fr_auto] gap-3 items-start font-mono text-[11px]"><span className="text-white/25">{new Date(e.ts).toLocaleTimeString()}</span><span className={`px-1.5 py-0.5 rounded border text-center uppercase text-[9px] font-black ${levelClass[e.level]||levelClass.info}`}>{e.level}</span><span className="min-w-0"><span className="block text-white/80 truncate">{e.message}</span><span className="block text-white/25 truncate mt-0.5">{e.category}{e.traceId?` · ${e.traceId}`:''}</span></span><span className="text-white/20">{e.durationMs!=null?`${e.durationMs}ms`:''}</span></button>)}</div>
        <aside className="border-t lg:border-t-0 lg:border-l border-white/10 min-h-0 overflow-auto bg-black/10">{selected?<div className="p-4 space-y-4"><div className="flex items-start gap-3"><div className={`w-9 h-9 rounded-lg border flex items-center justify-center ${levelClass[selected.level]}`}>{selected.level==='error'?<AlertTriangle size={17}/>:<CheckCircle2 size={17}/>}</div><div className="min-w-0"><div className="font-bold text-sm break-words">{selected.message}</div><div className="text-[10px] text-white/30 font-mono mt-1">{selected.ts} · {selected.category}{selected.durationMs!=null?` · ${selected.durationMs}ms`:''}</div></div></div>{selected.traceId&&<div><div className={labelClass}>Trace</div><code className="text-xs text-cyan break-all">{selected.traceId}</code></div>}<div><div className={labelClass}>Event data</div><pre className="text-[10px] leading-5 text-white/60 whitespace-pre-wrap break-words bg-black/20 rounded-xl p-3 border border-white/5">{JSON.stringify(selected.data||{},null,2)}</pre></div><button onClick={()=>setSelected(null)} className="text-xs text-white/30 hover:text-white">Close details</button></div>:<div className="p-5 text-sm text-white/25">Select an event to inspect its sanitized metadata and trace ID.</div>}</aside>
      </div>
      <footer className="shrink-0 border-t border-white/10 px-4 py-2 text-[10px] text-white/25 flex flex-wrap gap-4"><span>Persisted locally: last 800 events</span><span>Runtime buffer: 1500 events</span><span>Ctrl/Cmd + Shift + D toggles</span><span className="ml-auto">Auth tokens, cookies and request bodies are never stored</span></footer>
    </section>
  </div>
}
